# --- SMM partial-monotone mixer parameters ---

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"
buffer_size: 5000
target_update_interval: 200

agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "smm"

smm_state_embed_dim: 136
smm_state_encoder_depth: 1
smm_state_activation: "silu"
smm_K: 13
smm_h_K: 16
smm_b_z: 1.0
smm_b_t: 1.0
smm_beta: -1.0
smm_log_beta_min: -5.0
smm_log_beta_max: 5.0
smm_transform: "explin"
smm_scale_beta: False
smm_state_value_dim: 32
smm_state_value_activation: "relu"

name: "smm"
