# --- AMCO partial-monotone mixer parameters ---

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"
buffer_size: 5000
target_update_interval: 200

agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "amco"

amco_state_embed_dim: 128
amco_mono_hidden_dim: 128
amco_mono_depth: 4
amco_state_encoder_depth: 2
amco_state_activation: "silu"
amco_mono_activation: "selu"

name: "amco"
