action_selector: epsilon_expl
agent: rnn
agent_output_type: q
batch_size: 32
batch_size_run: 1
buffer_size: 5000
double_q: true
epsilon_anneal_time: 50000
epsilon_finish: 0.05
epsilon_start: 1.0
hypernet_embed: 64
hypernet_layers: 2
ices_int_critic_lr: 0.001
ices_int_entropy_coef: 0.1
ices_int_finish: 0.1
ices_int_lr: 0.01
ices_int_ratio: 0.1
ices_intrinsic_hidden_dim: 64
ices_world_hidden_dim: 64
ices_world_lr: 0.0001
learner: ices_q_learner
lr: 0.0005
mac: ices_mac
mixer: qmix
mixing_embed_dim: 32
name: ices
obs_agent_id: true
obs_last_action: true
optimizer: rmsprop
rnn_hidden_dim: 64
runner: episode
target_update_interval: 200
